use_frameworks!

platform :ios, '9.0'

target 'MyFirstCocoaPodTest_Example' do
  pod 'MyFirstCocoaPodTest', :path => '../'

  target 'MyFirstCocoaPodTest_Tests' do
    inherit! :search_paths

    
  end
end
